/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 78
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_doc_comment = 2,
  sym_line_comment = 3,
  sym_keyword_type = 4,
  sym_keyword_opt = 5,
  sym_keyword_arg = 6,
  sym_keyword_cmd = 7,
  sym_keyword_requires = 8,
  sym_keyword_excludes = 9,
  sym_keyword_effects = 10,
  sym_operator_and = 11,
  sym_open_paren = 12,
  sym_closed_paren = 13,
  sym_open_bracket = 14,
  sym_closed_bracket = 15,
  sym_open_chevron = 16,
  sym_closed_chevron = 17,
  sym_pipe = 18,
  sym_comma = 19,
  sym_range = 20,
  sym_named_identifier = 21,
  sym_int_literal = 22,
  sym_float_literal = 23,
  sym_string_literal = 24,
  sym_fat_arrow = 25,
  sym_source_file = 26,
  sym__comment = 27,
  sym__declaration = 28,
  sym__constraint_declaration = 29,
  sym_constraint_block = 30,
  sym__type_expression = 31,
  sym_nested_type = 32,
  sym_anonymous_enum_expression = 33,
  sym_integer_enum = 34,
  sym_float_enum = 35,
  sym_string_enum = 36,
  sym_type_declaration = 37,
  sym_requires_clause = 38,
  sym_excludes_clause = 39,
  sym_effects_clause = 40,
  sym_and_expression = 41,
  sym_or_expression = 42,
  sym__boolean_expression = 43,
  sym_opt_declaration = 44,
  sym_opt_unit = 45,
  sym_arg_declaration = 46,
  sym_arg_unit = 47,
  sym_cmd_declaration = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_constraint_block_repeat1 = 50,
  aux_sym_integer_enum_repeat1 = 51,
  aux_sym_float_enum_repeat1 = 52,
  aux_sym_string_enum_repeat1 = 53,
  aux_sym_opt_unit_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_doc_comment] = "doc_comment",
  [sym_line_comment] = "line_comment",
  [sym_keyword_type] = "keyword_type",
  [sym_keyword_opt] = "keyword_opt",
  [sym_keyword_arg] = "keyword_arg",
  [sym_keyword_cmd] = "keyword_cmd",
  [sym_keyword_requires] = "keyword_requires",
  [sym_keyword_excludes] = "keyword_excludes",
  [sym_keyword_effects] = "keyword_effects",
  [sym_operator_and] = "operator_and",
  [sym_open_paren] = "open_paren",
  [sym_closed_paren] = "closed_paren",
  [sym_open_bracket] = "open_bracket",
  [sym_closed_bracket] = "closed_bracket",
  [sym_open_chevron] = "open_chevron",
  [sym_closed_chevron] = "closed_chevron",
  [sym_pipe] = "pipe",
  [sym_comma] = "comma",
  [sym_range] = "range",
  [sym_named_identifier] = "named_identifier",
  [sym_int_literal] = "int_literal",
  [sym_float_literal] = "float_literal",
  [sym_string_literal] = "string_literal",
  [sym_fat_arrow] = "fat_arrow",
  [sym_source_file] = "source_file",
  [sym__comment] = "_comment",
  [sym__declaration] = "_declaration",
  [sym__constraint_declaration] = "_constraint_declaration",
  [sym_constraint_block] = "constraint_block",
  [sym__type_expression] = "_type_expression",
  [sym_nested_type] = "nested_type",
  [sym_anonymous_enum_expression] = "anonymous_enum_expression",
  [sym_integer_enum] = "integer_enum",
  [sym_float_enum] = "float_enum",
  [sym_string_enum] = "string_enum",
  [sym_type_declaration] = "type_declaration",
  [sym_requires_clause] = "requires_clause",
  [sym_excludes_clause] = "excludes_clause",
  [sym_effects_clause] = "effects_clause",
  [sym_and_expression] = "and_expression",
  [sym_or_expression] = "or_expression",
  [sym__boolean_expression] = "_boolean_expression",
  [sym_opt_declaration] = "opt_declaration",
  [sym_opt_unit] = "opt_unit",
  [sym_arg_declaration] = "arg_declaration",
  [sym_arg_unit] = "arg_unit",
  [sym_cmd_declaration] = "cmd_declaration",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_constraint_block_repeat1] = "constraint_block_repeat1",
  [aux_sym_integer_enum_repeat1] = "integer_enum_repeat1",
  [aux_sym_float_enum_repeat1] = "float_enum_repeat1",
  [aux_sym_string_enum_repeat1] = "string_enum_repeat1",
  [aux_sym_opt_unit_repeat1] = "opt_unit_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_doc_comment] = sym_doc_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_keyword_type] = sym_keyword_type,
  [sym_keyword_opt] = sym_keyword_opt,
  [sym_keyword_arg] = sym_keyword_arg,
  [sym_keyword_cmd] = sym_keyword_cmd,
  [sym_keyword_requires] = sym_keyword_requires,
  [sym_keyword_excludes] = sym_keyword_excludes,
  [sym_keyword_effects] = sym_keyword_effects,
  [sym_operator_and] = sym_operator_and,
  [sym_open_paren] = sym_open_paren,
  [sym_closed_paren] = sym_closed_paren,
  [sym_open_bracket] = sym_open_bracket,
  [sym_closed_bracket] = sym_closed_bracket,
  [sym_open_chevron] = sym_open_chevron,
  [sym_closed_chevron] = sym_closed_chevron,
  [sym_pipe] = sym_pipe,
  [sym_comma] = sym_comma,
  [sym_range] = sym_range,
  [sym_named_identifier] = sym_named_identifier,
  [sym_int_literal] = sym_int_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_fat_arrow] = sym_fat_arrow,
  [sym_source_file] = sym_source_file,
  [sym__comment] = sym__comment,
  [sym__declaration] = sym__declaration,
  [sym__constraint_declaration] = sym__constraint_declaration,
  [sym_constraint_block] = sym_constraint_block,
  [sym__type_expression] = sym__type_expression,
  [sym_nested_type] = sym_nested_type,
  [sym_anonymous_enum_expression] = sym_anonymous_enum_expression,
  [sym_integer_enum] = sym_integer_enum,
  [sym_float_enum] = sym_float_enum,
  [sym_string_enum] = sym_string_enum,
  [sym_type_declaration] = sym_type_declaration,
  [sym_requires_clause] = sym_requires_clause,
  [sym_excludes_clause] = sym_excludes_clause,
  [sym_effects_clause] = sym_effects_clause,
  [sym_and_expression] = sym_and_expression,
  [sym_or_expression] = sym_or_expression,
  [sym__boolean_expression] = sym__boolean_expression,
  [sym_opt_declaration] = sym_opt_declaration,
  [sym_opt_unit] = sym_opt_unit,
  [sym_arg_declaration] = sym_arg_declaration,
  [sym_arg_unit] = sym_arg_unit,
  [sym_cmd_declaration] = sym_cmd_declaration,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_constraint_block_repeat1] = aux_sym_constraint_block_repeat1,
  [aux_sym_integer_enum_repeat1] = aux_sym_integer_enum_repeat1,
  [aux_sym_float_enum_repeat1] = aux_sym_float_enum_repeat1,
  [aux_sym_string_enum_repeat1] = aux_sym_string_enum_repeat1,
  [aux_sym_opt_unit_repeat1] = aux_sym_opt_unit_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_type] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_opt] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_cmd] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_requires] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_excludes] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_effects] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_and] = {
    .visible = true,
    .named = true,
  },
  [sym_open_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_closed_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_open_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_closed_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_open_chevron] = {
    .visible = true,
    .named = true,
  },
  [sym_closed_chevron] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe] = {
    .visible = true,
    .named = true,
  },
  [sym_comma] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_named_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_fat_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym__constraint_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_constraint_block] = {
    .visible = true,
    .named = true,
  },
  [sym__type_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_nested_type] = {
    .visible = true,
    .named = true,
  },
  [sym_anonymous_enum_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_float_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_string_enum] = {
    .visible = true,
    .named = true,
  },
  [sym_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_requires_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_excludes_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_effects_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_and_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_or_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__boolean_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_opt_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_opt_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd_declaration] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constraint_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_enum_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opt_unit_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_end = 1,
  field_inner = 2,
  field_outer = 3,
  field_start = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_end] = "end",
  [field_inner] = "inner",
  [field_outer] = "outer",
  [field_start] = "start",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_end, 3},
  [1] =
    {field_start, 2},
  [2] =
    {field_inner, 2},
    {field_outer, 0},
  [4] =
    {field_end, 4},
    {field_start, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '"', 2,
        '&', 16,
        '(', 17,
        ')', 18,
        ',', 24,
        '-', 6,
        '.', 3,
        '/', 4,
        '<', 21,
        '=', 5,
        '>', 22,
        '{', 19,
        '|', 23,
        '}', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(15);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == '-') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '&', 16,
        ')', 18,
        '-', 8,
        '.', 3,
        '/', 4,
        '<', 21,
        '>', 22,
        '{', 19,
        '|', 23,
        '}', 20,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_doc_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_operator_and);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_open_paren);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_closed_paren);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_open_bracket);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_closed_bracket);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_open_chevron);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_closed_chevron);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_pipe);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comma);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_range);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_named_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_int_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_fat_arrow);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'm') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(9);
      if (lookahead == 'x') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'y') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'g') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'q') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_keyword_arg);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_keyword_cmd);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_keyword_opt);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(23);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_keyword_type);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 26:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_keyword_effects);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_keyword_excludes);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_keyword_requires);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 10},
  [11] = {.lex_state = 10},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 10},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 10},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_doc_comment] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [sym_keyword_type] = ACTIONS(1),
    [sym_keyword_opt] = ACTIONS(1),
    [sym_keyword_arg] = ACTIONS(1),
    [sym_keyword_cmd] = ACTIONS(1),
    [sym_keyword_requires] = ACTIONS(1),
    [sym_keyword_excludes] = ACTIONS(1),
    [sym_keyword_effects] = ACTIONS(1),
    [sym_operator_and] = ACTIONS(1),
    [sym_open_paren] = ACTIONS(1),
    [sym_closed_paren] = ACTIONS(1),
    [sym_open_bracket] = ACTIONS(1),
    [sym_closed_bracket] = ACTIONS(1),
    [sym_open_chevron] = ACTIONS(1),
    [sym_closed_chevron] = ACTIONS(1),
    [sym_pipe] = ACTIONS(1),
    [sym_comma] = ACTIONS(1),
    [sym_range] = ACTIONS(1),
    [sym_named_identifier] = ACTIONS(1),
    [sym_int_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_fat_arrow] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(70),
    [sym__comment] = STATE(2),
    [sym__declaration] = STATE(2),
    [sym_type_declaration] = STATE(2),
    [sym_opt_declaration] = STATE(2),
    [sym_arg_declaration] = STATE(2),
    [sym_cmd_declaration] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(7),
    [sym_keyword_type] = ACTIONS(9),
    [sym_keyword_opt] = ACTIONS(11),
    [sym_keyword_arg] = ACTIONS(13),
    [sym_keyword_cmd] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      sym_keyword_type,
    ACTIONS(11), 1,
      sym_keyword_opt,
    ACTIONS(13), 1,
      sym_keyword_arg,
    ACTIONS(15), 1,
      sym_keyword_cmd,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_doc_comment,
    ACTIONS(21), 1,
      sym_line_comment,
    STATE(3), 7,
      sym__comment,
      sym__declaration,
      sym_type_declaration,
      sym_opt_declaration,
      sym_arg_declaration,
      sym_cmd_declaration,
      aux_sym_source_file_repeat1,
  [31] = 8,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_doc_comment,
    ACTIONS(28), 1,
      sym_line_comment,
    ACTIONS(31), 1,
      sym_keyword_type,
    ACTIONS(34), 1,
      sym_keyword_opt,
    ACTIONS(37), 1,
      sym_keyword_arg,
    ACTIONS(40), 1,
      sym_keyword_cmd,
    STATE(3), 7,
      sym__comment,
      sym__declaration,
      sym_type_declaration,
      sym_opt_declaration,
      sym_arg_declaration,
      sym_cmd_declaration,
      aux_sym_source_file_repeat1,
  [62] = 4,
    ACTIONS(45), 1,
      sym_line_comment,
    ACTIONS(47), 1,
      sym_pipe,
    STATE(12), 1,
      aux_sym_integer_enum_repeat1,
    ACTIONS(43), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [82] = 4,
    ACTIONS(51), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      sym_pipe,
    STATE(10), 1,
      aux_sym_float_enum_repeat1,
    ACTIONS(49), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [102] = 4,
    ACTIONS(47), 1,
      sym_pipe,
    ACTIONS(57), 1,
      sym_line_comment,
    STATE(4), 1,
      aux_sym_integer_enum_repeat1,
    ACTIONS(55), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [122] = 4,
    ACTIONS(61), 1,
      sym_line_comment,
    ACTIONS(63), 1,
      sym_pipe,
    STATE(9), 1,
      aux_sym_string_enum_repeat1,
    ACTIONS(59), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [142] = 4,
    ACTIONS(53), 1,
      sym_pipe,
    ACTIONS(67), 1,
      sym_line_comment,
    STATE(5), 1,
      aux_sym_float_enum_repeat1,
    ACTIONS(65), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [162] = 4,
    ACTIONS(63), 1,
      sym_pipe,
    ACTIONS(71), 1,
      sym_line_comment,
    STATE(11), 1,
      aux_sym_string_enum_repeat1,
    ACTIONS(69), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [182] = 4,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(77), 1,
      sym_pipe,
    STATE(10), 1,
      aux_sym_float_enum_repeat1,
    ACTIONS(73), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [202] = 4,
    ACTIONS(82), 1,
      sym_line_comment,
    ACTIONS(84), 1,
      sym_pipe,
    STATE(11), 1,
      aux_sym_string_enum_repeat1,
    ACTIONS(80), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [222] = 4,
    ACTIONS(89), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      sym_pipe,
    STATE(12), 1,
      aux_sym_integer_enum_repeat1,
    ACTIONS(87), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [242] = 3,
    ACTIONS(96), 1,
      sym_line_comment,
    ACTIONS(98), 1,
      sym_open_chevron,
    ACTIONS(94), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [259] = 6,
    ACTIONS(100), 1,
      sym_named_identifier,
    ACTIONS(102), 1,
      sym_int_literal,
    ACTIONS(104), 1,
      sym_float_literal,
    ACTIONS(106), 1,
      sym_string_literal,
    STATE(22), 3,
      sym_integer_enum,
      sym_float_enum,
      sym_string_enum,
    STATE(27), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [282] = 6,
    ACTIONS(100), 1,
      sym_named_identifier,
    ACTIONS(102), 1,
      sym_int_literal,
    ACTIONS(104), 1,
      sym_float_literal,
    ACTIONS(106), 1,
      sym_string_literal,
    STATE(22), 3,
      sym_integer_enum,
      sym_float_enum,
      sym_string_enum,
    STATE(28), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [305] = 6,
    ACTIONS(100), 1,
      sym_named_identifier,
    ACTIONS(102), 1,
      sym_int_literal,
    ACTIONS(104), 1,
      sym_float_literal,
    ACTIONS(106), 1,
      sym_string_literal,
    STATE(22), 3,
      sym_integer_enum,
      sym_float_enum,
      sym_string_enum,
    STATE(74), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [328] = 2,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(73), 9,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
      sym_pipe,
  [343] = 2,
    ACTIONS(89), 1,
      sym_line_comment,
    ACTIONS(87), 9,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
      sym_pipe,
  [358] = 2,
    ACTIONS(82), 1,
      sym_line_comment,
    ACTIONS(80), 9,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
      sym_pipe,
  [373] = 6,
    ACTIONS(100), 1,
      sym_named_identifier,
    ACTIONS(102), 1,
      sym_int_literal,
    ACTIONS(104), 1,
      sym_float_literal,
    ACTIONS(106), 1,
      sym_string_literal,
    STATE(21), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
    STATE(22), 3,
      sym_integer_enum,
      sym_float_enum,
      sym_string_enum,
  [396] = 4,
    ACTIONS(110), 1,
      sym_line_comment,
    ACTIONS(112), 1,
      sym_open_bracket,
    STATE(32), 1,
      sym_constraint_block,
    ACTIONS(108), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [414] = 2,
    ACTIONS(116), 1,
      sym_line_comment,
    ACTIONS(114), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [428] = 5,
    ACTIONS(118), 1,
      sym_keyword_requires,
    ACTIONS(120), 1,
      sym_keyword_excludes,
    ACTIONS(122), 1,
      sym_keyword_effects,
    ACTIONS(124), 1,
      sym_closed_bracket,
    STATE(26), 5,
      sym__constraint_declaration,
      sym_requires_clause,
      sym_excludes_clause,
      sym_effects_clause,
      aux_sym_constraint_block_repeat1,
  [448] = 5,
    ACTIONS(126), 1,
      sym_keyword_requires,
    ACTIONS(129), 1,
      sym_keyword_excludes,
    ACTIONS(132), 1,
      sym_keyword_effects,
    ACTIONS(135), 1,
      sym_closed_bracket,
    STATE(24), 5,
      sym__constraint_declaration,
      sym_requires_clause,
      sym_excludes_clause,
      sym_effects_clause,
      aux_sym_constraint_block_repeat1,
  [468] = 2,
    ACTIONS(139), 1,
      sym_line_comment,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_chevron,
  [482] = 5,
    ACTIONS(118), 1,
      sym_keyword_requires,
    ACTIONS(120), 1,
      sym_keyword_excludes,
    ACTIONS(122), 1,
      sym_keyword_effects,
    ACTIONS(141), 1,
      sym_closed_bracket,
    STATE(24), 5,
      sym__constraint_declaration,
      sym_requires_clause,
      sym_excludes_clause,
      sym_effects_clause,
      aux_sym_constraint_block_repeat1,
  [502] = 2,
    ACTIONS(145), 1,
      sym_line_comment,
    ACTIONS(143), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [514] = 2,
    ACTIONS(149), 1,
      sym_line_comment,
    ACTIONS(147), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [526] = 2,
    ACTIONS(153), 1,
      sym_line_comment,
    ACTIONS(151), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [538] = 2,
    ACTIONS(157), 1,
      sym_line_comment,
    ACTIONS(155), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [550] = 2,
    ACTIONS(161), 1,
      sym_line_comment,
    ACTIONS(159), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [562] = 2,
    ACTIONS(165), 1,
      sym_line_comment,
    ACTIONS(163), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [574] = 1,
    ACTIONS(167), 7,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_operator_and,
      sym_closed_paren,
      sym_closed_bracket,
      sym_pipe,
  [584] = 1,
    ACTIONS(169), 7,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_operator_and,
      sym_closed_paren,
      sym_closed_bracket,
      sym_pipe,
  [594] = 2,
    ACTIONS(173), 1,
      sym_operator_and,
    ACTIONS(171), 6,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_closed_paren,
      sym_closed_bracket,
      sym_pipe,
  [606] = 3,
    ACTIONS(173), 1,
      sym_operator_and,
    ACTIONS(177), 1,
      sym_pipe,
    ACTIONS(175), 4,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_closed_bracket,
  [619] = 3,
    ACTIONS(173), 1,
      sym_operator_and,
    ACTIONS(177), 1,
      sym_pipe,
    ACTIONS(179), 4,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_closed_bracket,
  [632] = 3,
    ACTIONS(173), 1,
      sym_operator_and,
    ACTIONS(177), 1,
      sym_pipe,
    ACTIONS(181), 4,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_closed_bracket,
  [645] = 3,
    ACTIONS(183), 1,
      sym_open_paren,
    ACTIONS(185), 1,
      sym_named_identifier,
    STATE(37), 3,
      sym_and_expression,
      sym_or_expression,
      sym__boolean_expression,
  [657] = 3,
    ACTIONS(183), 1,
      sym_open_paren,
    ACTIONS(187), 1,
      sym_named_identifier,
    STATE(36), 3,
      sym_and_expression,
      sym_or_expression,
      sym__boolean_expression,
  [669] = 3,
    ACTIONS(183), 1,
      sym_open_paren,
    ACTIONS(189), 1,
      sym_named_identifier,
    STATE(38), 3,
      sym_and_expression,
      sym_or_expression,
      sym__boolean_expression,
  [681] = 3,
    ACTIONS(183), 1,
      sym_open_paren,
    ACTIONS(191), 1,
      sym_named_identifier,
    STATE(48), 3,
      sym_and_expression,
      sym_or_expression,
      sym__boolean_expression,
  [693] = 3,
    ACTIONS(183), 1,
      sym_open_paren,
    ACTIONS(193), 1,
      sym_named_identifier,
    STATE(35), 3,
      sym_and_expression,
      sym_or_expression,
      sym__boolean_expression,
  [705] = 3,
    ACTIONS(183), 1,
      sym_open_paren,
    ACTIONS(195), 1,
      sym_named_identifier,
    STATE(34), 3,
      sym_and_expression,
      sym_or_expression,
      sym__boolean_expression,
  [717] = 3,
    ACTIONS(197), 1,
      sym_closed_paren,
    ACTIONS(199), 1,
      sym_comma,
    STATE(46), 1,
      aux_sym_opt_unit_repeat1,
  [727] = 3,
    ACTIONS(199), 1,
      sym_comma,
    ACTIONS(201), 1,
      sym_closed_paren,
    STATE(47), 1,
      aux_sym_opt_unit_repeat1,
  [737] = 3,
    ACTIONS(203), 1,
      sym_closed_paren,
    ACTIONS(205), 1,
      sym_comma,
    STATE(47), 1,
      aux_sym_opt_unit_repeat1,
  [747] = 3,
    ACTIONS(173), 1,
      sym_operator_and,
    ACTIONS(177), 1,
      sym_pipe,
    ACTIONS(208), 1,
      sym_closed_paren,
  [757] = 2,
    ACTIONS(210), 1,
      sym_closed_paren,
    ACTIONS(212), 1,
      sym_int_literal,
  [764] = 2,
    ACTIONS(214), 1,
      sym_named_identifier,
    STATE(60), 1,
      sym_arg_unit,
  [771] = 2,
    ACTIONS(216), 1,
      sym_range,
    ACTIONS(218), 1,
      sym_int_literal,
  [778] = 2,
    ACTIONS(220), 1,
      sym_named_identifier,
    STATE(76), 1,
      sym_opt_unit,
  [785] = 1,
    ACTIONS(203), 2,
      sym_closed_paren,
      sym_comma,
  [790] = 2,
    ACTIONS(222), 1,
      sym_closed_paren,
    ACTIONS(224), 1,
      sym_int_literal,
  [797] = 1,
    ACTIONS(226), 1,
      sym_range,
  [801] = 1,
    ACTIONS(228), 1,
      sym_fat_arrow,
  [805] = 1,
    ACTIONS(230), 1,
      sym_named_identifier,
  [809] = 1,
    ACTIONS(232), 1,
      sym_open_paren,
  [813] = 1,
    ACTIONS(234), 1,
      sym_fat_arrow,
  [817] = 1,
    ACTIONS(236), 1,
      sym_fat_arrow,
  [821] = 1,
    ACTIONS(238), 1,
      sym_fat_arrow,
  [825] = 1,
    ACTIONS(240), 1,
      sym_fat_arrow,
  [829] = 1,
    ACTIONS(242), 1,
      sym_closed_paren,
  [833] = 1,
    ACTIONS(244), 1,
      sym_string_literal,
  [837] = 1,
    ACTIONS(246), 1,
      sym_string_literal,
  [841] = 1,
    ACTIONS(248), 1,
      sym_open_paren,
  [845] = 1,
    ACTIONS(250), 1,
      sym_string_literal,
  [849] = 1,
    ACTIONS(252), 1,
      sym_fat_arrow,
  [853] = 1,
    ACTIONS(254), 1,
      sym_int_literal,
  [857] = 1,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
  [861] = 1,
    ACTIONS(258), 1,
      sym_fat_arrow,
  [865] = 1,
    ACTIONS(260), 1,
      sym_closed_paren,
  [869] = 1,
    ACTIONS(262), 1,
      sym_fat_arrow,
  [873] = 1,
    ACTIONS(264), 1,
      sym_closed_chevron,
  [877] = 1,
    ACTIONS(266), 1,
      sym_float_literal,
  [881] = 1,
    ACTIONS(268), 1,
      sym_fat_arrow,
  [885] = 1,
    ACTIONS(270), 1,
      sym_string_literal,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 82,
  [SMALL_STATE(6)] = 102,
  [SMALL_STATE(7)] = 122,
  [SMALL_STATE(8)] = 142,
  [SMALL_STATE(9)] = 162,
  [SMALL_STATE(10)] = 182,
  [SMALL_STATE(11)] = 202,
  [SMALL_STATE(12)] = 222,
  [SMALL_STATE(13)] = 242,
  [SMALL_STATE(14)] = 259,
  [SMALL_STATE(15)] = 282,
  [SMALL_STATE(16)] = 305,
  [SMALL_STATE(17)] = 328,
  [SMALL_STATE(18)] = 343,
  [SMALL_STATE(19)] = 358,
  [SMALL_STATE(20)] = 373,
  [SMALL_STATE(21)] = 396,
  [SMALL_STATE(22)] = 414,
  [SMALL_STATE(23)] = 428,
  [SMALL_STATE(24)] = 448,
  [SMALL_STATE(25)] = 468,
  [SMALL_STATE(26)] = 482,
  [SMALL_STATE(27)] = 502,
  [SMALL_STATE(28)] = 514,
  [SMALL_STATE(29)] = 526,
  [SMALL_STATE(30)] = 538,
  [SMALL_STATE(31)] = 550,
  [SMALL_STATE(32)] = 562,
  [SMALL_STATE(33)] = 574,
  [SMALL_STATE(34)] = 584,
  [SMALL_STATE(35)] = 594,
  [SMALL_STATE(36)] = 606,
  [SMALL_STATE(37)] = 619,
  [SMALL_STATE(38)] = 632,
  [SMALL_STATE(39)] = 645,
  [SMALL_STATE(40)] = 657,
  [SMALL_STATE(41)] = 669,
  [SMALL_STATE(42)] = 681,
  [SMALL_STATE(43)] = 693,
  [SMALL_STATE(44)] = 705,
  [SMALL_STATE(45)] = 717,
  [SMALL_STATE(46)] = 727,
  [SMALL_STATE(47)] = 737,
  [SMALL_STATE(48)] = 747,
  [SMALL_STATE(49)] = 757,
  [SMALL_STATE(50)] = 764,
  [SMALL_STATE(51)] = 771,
  [SMALL_STATE(52)] = 778,
  [SMALL_STATE(53)] = 785,
  [SMALL_STATE(54)] = 790,
  [SMALL_STATE(55)] = 797,
  [SMALL_STATE(56)] = 801,
  [SMALL_STATE(57)] = 805,
  [SMALL_STATE(58)] = 809,
  [SMALL_STATE(59)] = 813,
  [SMALL_STATE(60)] = 817,
  [SMALL_STATE(61)] = 821,
  [SMALL_STATE(62)] = 825,
  [SMALL_STATE(63)] = 829,
  [SMALL_STATE(64)] = 833,
  [SMALL_STATE(65)] = 837,
  [SMALL_STATE(66)] = 841,
  [SMALL_STATE(67)] = 845,
  [SMALL_STATE(68)] = 849,
  [SMALL_STATE(69)] = 853,
  [SMALL_STATE(70)] = 857,
  [SMALL_STATE(71)] = 861,
  [SMALL_STATE(72)] = 865,
  [SMALL_STATE(73)] = 869,
  [SMALL_STATE(74)] = 873,
  [SMALL_STATE(75)] = 877,
  [SMALL_STATE(76)] = 881,
  [SMALL_STATE(77)] = 885,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_enum, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer_enum, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_enum, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_enum, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_enum, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer_enum, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_enum, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_enum, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_enum, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_enum, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_enum, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_enum, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_float_enum_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_float_enum_repeat1, 2, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_float_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_enum_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_enum_repeat1, 2, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_integer_enum_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_integer_enum_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_integer_enum_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_expression, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type_expression, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_declaration, 4, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_enum_expression, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonymous_enum_expression, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_type, 4, 0, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_type, 4, 0, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_declaration, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_declaration, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opt_declaration, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opt_declaration, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_declaration, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_declaration, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_block, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_block, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_block, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_block, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 5, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_declaration, 5, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__boolean_expression, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and_expression, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_expression, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_excludes_clause, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effects_clause, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_clause, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_opt_unit_repeat1, 2, 0, 0),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_opt_unit_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opt_unit, 5, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_unit, 5, 0, 1),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_unit, 5, 0, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_unit, 4, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [256] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_unit, 6, 0, 4),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opt_unit, 4, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_clispec(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "clispec",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
