/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 130
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_doc_comment = 2,
  sym_line_comment = 3,
  sym_keyword_type = 4,
  sym_keyword_opt = 5,
  sym_keyword_arg = 6,
  sym_keyword_cmd = 7,
  sym_keyword_requires = 8,
  sym_keyword_excludes = 9,
  sym_keyword_effects = 10,
  sym_keyword_subcommands = 11,
  sym_operator_and = 12,
  sym_operator_or = 13,
  sym_open_paren = 14,
  sym_closed_paren = 15,
  sym_open_bracket = 16,
  sym_closed_bracket = 17,
  sym_open_square = 18,
  sym_closed_square = 19,
  sym_open_chevron = 20,
  sym_closed_chevron = 21,
  sym_comma = 22,
  sym_range = 23,
  sym_named_identifier = 24,
  sym_int_literal = 25,
  sym_float_literal = 26,
  sym_string_literal = 27,
  sym_bool_literal = 28,
  sym_fat_arrow = 29,
  sym_source_file = 30,
  sym__declaration = 31,
  sym_declaration_block = 32,
  sym__constraint_declaration = 33,
  sym_constraint_block = 34,
  sym__type_expression = 35,
  sym_nested_type = 36,
  sym_literals = 37,
  sym_anonymous_enum_expression = 38,
  sym_type_declaration = 39,
  sym_requires_clause = 40,
  sym_excludes_clause = 41,
  sym_effects_clause = 42,
  sym_subcommands_clause = 43,
  sym_and_expression = 44,
  sym_or_expression = 45,
  sym_paren_expression = 46,
  sym__boolean_expression = 47,
  sym_opt_declaration = 48,
  sym_opt_unit = 49,
  sym_arg_declaration = 50,
  sym_arg_unit = 51,
  sym_cmd_declaration = 52,
  sym_cmd_unit = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_constraint_block_repeat1 = 55,
  aux_sym_anonymous_enum_expression_repeat1 = 56,
  aux_sym_opt_unit_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_doc_comment] = "doc_comment",
  [sym_line_comment] = "line_comment",
  [sym_keyword_type] = "keyword_type",
  [sym_keyword_opt] = "keyword_opt",
  [sym_keyword_arg] = "keyword_arg",
  [sym_keyword_cmd] = "keyword_cmd",
  [sym_keyword_requires] = "keyword_requires",
  [sym_keyword_excludes] = "keyword_excludes",
  [sym_keyword_effects] = "keyword_effects",
  [sym_keyword_subcommands] = "keyword_subcommands",
  [sym_operator_and] = "operator_and",
  [sym_operator_or] = "operator_or",
  [sym_open_paren] = "open_paren",
  [sym_closed_paren] = "closed_paren",
  [sym_open_bracket] = "open_bracket",
  [sym_closed_bracket] = "closed_bracket",
  [sym_open_square] = "open_square",
  [sym_closed_square] = "closed_square",
  [sym_open_chevron] = "open_chevron",
  [sym_closed_chevron] = "closed_chevron",
  [sym_comma] = "comma",
  [sym_range] = "range",
  [sym_named_identifier] = "named_identifier",
  [sym_int_literal] = "int_literal",
  [sym_float_literal] = "float_literal",
  [sym_string_literal] = "string_literal",
  [sym_bool_literal] = "bool_literal",
  [sym_fat_arrow] = "fat_arrow",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_declaration_block] = "declaration_block",
  [sym__constraint_declaration] = "_constraint_declaration",
  [sym_constraint_block] = "constraint_block",
  [sym__type_expression] = "_type_expression",
  [sym_nested_type] = "nested_type",
  [sym_literals] = "literals",
  [sym_anonymous_enum_expression] = "anonymous_enum_expression",
  [sym_type_declaration] = "type_declaration",
  [sym_requires_clause] = "requires_clause",
  [sym_excludes_clause] = "excludes_clause",
  [sym_effects_clause] = "effects_clause",
  [sym_subcommands_clause] = "subcommands_clause",
  [sym_and_expression] = "and_expression",
  [sym_or_expression] = "or_expression",
  [sym_paren_expression] = "paren_expression",
  [sym__boolean_expression] = "_boolean_expression",
  [sym_opt_declaration] = "opt_declaration",
  [sym_opt_unit] = "opt_unit",
  [sym_arg_declaration] = "arg_declaration",
  [sym_arg_unit] = "arg_unit",
  [sym_cmd_declaration] = "cmd_declaration",
  [sym_cmd_unit] = "cmd_unit",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_constraint_block_repeat1] = "constraint_block_repeat1",
  [aux_sym_anonymous_enum_expression_repeat1] = "anonymous_enum_expression_repeat1",
  [aux_sym_opt_unit_repeat1] = "opt_unit_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_doc_comment] = sym_doc_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_keyword_type] = sym_keyword_type,
  [sym_keyword_opt] = sym_keyword_opt,
  [sym_keyword_arg] = sym_keyword_arg,
  [sym_keyword_cmd] = sym_keyword_cmd,
  [sym_keyword_requires] = sym_keyword_requires,
  [sym_keyword_excludes] = sym_keyword_excludes,
  [sym_keyword_effects] = sym_keyword_effects,
  [sym_keyword_subcommands] = sym_keyword_subcommands,
  [sym_operator_and] = sym_operator_and,
  [sym_operator_or] = sym_operator_or,
  [sym_open_paren] = sym_open_paren,
  [sym_closed_paren] = sym_closed_paren,
  [sym_open_bracket] = sym_open_bracket,
  [sym_closed_bracket] = sym_closed_bracket,
  [sym_open_square] = sym_open_square,
  [sym_closed_square] = sym_closed_square,
  [sym_open_chevron] = sym_open_chevron,
  [sym_closed_chevron] = sym_closed_chevron,
  [sym_comma] = sym_comma,
  [sym_range] = sym_range,
  [sym_named_identifier] = sym_named_identifier,
  [sym_int_literal] = sym_int_literal,
  [sym_float_literal] = sym_float_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_bool_literal] = sym_bool_literal,
  [sym_fat_arrow] = sym_fat_arrow,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_declaration_block] = sym_declaration_block,
  [sym__constraint_declaration] = sym__constraint_declaration,
  [sym_constraint_block] = sym_constraint_block,
  [sym__type_expression] = sym__type_expression,
  [sym_nested_type] = sym_nested_type,
  [sym_literals] = sym_literals,
  [sym_anonymous_enum_expression] = sym_anonymous_enum_expression,
  [sym_type_declaration] = sym_type_declaration,
  [sym_requires_clause] = sym_requires_clause,
  [sym_excludes_clause] = sym_excludes_clause,
  [sym_effects_clause] = sym_effects_clause,
  [sym_subcommands_clause] = sym_subcommands_clause,
  [sym_and_expression] = sym_and_expression,
  [sym_or_expression] = sym_or_expression,
  [sym_paren_expression] = sym_paren_expression,
  [sym__boolean_expression] = sym__boolean_expression,
  [sym_opt_declaration] = sym_opt_declaration,
  [sym_opt_unit] = sym_opt_unit,
  [sym_arg_declaration] = sym_arg_declaration,
  [sym_arg_unit] = sym_arg_unit,
  [sym_cmd_declaration] = sym_cmd_declaration,
  [sym_cmd_unit] = sym_cmd_unit,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_constraint_block_repeat1] = aux_sym_constraint_block_repeat1,
  [aux_sym_anonymous_enum_expression_repeat1] = aux_sym_anonymous_enum_expression_repeat1,
  [aux_sym_opt_unit_repeat1] = aux_sym_opt_unit_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_type] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_opt] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_cmd] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_requires] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_excludes] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_effects] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_subcommands] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_and] = {
    .visible = true,
    .named = true,
  },
  [sym_operator_or] = {
    .visible = true,
    .named = true,
  },
  [sym_open_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_closed_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_open_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_closed_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_open_square] = {
    .visible = true,
    .named = true,
  },
  [sym_closed_square] = {
    .visible = true,
    .named = true,
  },
  [sym_open_chevron] = {
    .visible = true,
    .named = true,
  },
  [sym_closed_chevron] = {
    .visible = true,
    .named = true,
  },
  [sym_comma] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_named_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_fat_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_declaration_block] = {
    .visible = true,
    .named = true,
  },
  [sym__constraint_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_constraint_block] = {
    .visible = true,
    .named = true,
  },
  [sym__type_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_nested_type] = {
    .visible = true,
    .named = true,
  },
  [sym_literals] = {
    .visible = true,
    .named = true,
  },
  [sym_anonymous_enum_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_requires_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_excludes_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_effects_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_subcommands_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_and_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_or_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__boolean_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_opt_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_opt_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd_unit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constraint_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_anonymous_enum_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opt_unit_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_end = 1,
  field_inner = 2,
  field_outer = 3,
  field_start = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_end] = "end",
  [field_inner] = "inner",
  [field_outer] = "outer",
  [field_start] = "start",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_end, 3},
  [1] =
    {field_start, 2},
  [2] =
    {field_inner, 2},
    {field_outer, 0},
  [4] =
    {field_end, 4},
    {field_start, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 3,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 11,
  [17] = 10,
  [18] = 13,
  [19] = 19,
  [20] = 20,
  [21] = 12,
  [22] = 14,
  [23] = 9,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 25,
  [34] = 24,
  [35] = 19,
  [36] = 36,
  [37] = 37,
  [38] = 27,
  [39] = 26,
  [40] = 20,
  [41] = 41,
  [42] = 29,
  [43] = 32,
  [44] = 28,
  [45] = 30,
  [46] = 37,
  [47] = 41,
  [48] = 36,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 51,
  [55] = 31,
  [56] = 50,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 61,
  [64] = 64,
  [65] = 57,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 67,
  [70] = 62,
  [71] = 66,
  [72] = 68,
  [73] = 64,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 82,
  [84] = 84,
  [85] = 84,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 89,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 93,
  [97] = 97,
  [98] = 97,
  [99] = 99,
  [100] = 100,
  [101] = 95,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 102,
  [121] = 121,
  [122] = 116,
  [123] = 119,
  [124] = 112,
  [125] = 125,
  [126] = 110,
  [127] = 121,
  [128] = 128,
  [129] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '"', 3,
        '&', 29,
        '(', 31,
        ')', 32,
        ',', 39,
        '-', 13,
        '.', 4,
        '/', 5,
        '<', 37,
        '=', 6,
        '>', 38,
        '[', 35,
        ']', 36,
        'f', 22,
        't', 25,
        '{', 33,
        '|', 30,
        '}', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(41);
      if (lookahead == 't') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == 't') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(53);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '&', 29,
        ')', 32,
        '-', 15,
        '.', 4,
        '/', 5,
        '<', 37,
        '>', 38,
        '[', 35,
        ']', 36,
        '{', 33,
        '|', 30,
        '}', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_doc_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_operator_and);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_operator_or);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_open_paren);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_closed_paren);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_open_bracket);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_closed_bracket);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_open_square);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_closed_square);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_open_chevron);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_closed_chevron);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_comma);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_range);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_named_identifier);
      if (lookahead == 'a') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_named_identifier);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_named_identifier);
      if (lookahead == 'l') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_named_identifier);
      if (lookahead == 'r') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_named_identifier);
      if (lookahead == 's') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_named_identifier);
      if (lookahead == 'u') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_named_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_int_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_bool_literal);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_fat_arrow);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'm') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 'x') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'y') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'g') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'q') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'b') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_keyword_arg);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_keyword_cmd);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_keyword_opt);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_keyword_type);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(34);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 32:
      if (lookahead == 'm') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 36:
      if (lookahead == 'm') ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_keyword_effects);
      END_STATE();
    case 38:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 40:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_keyword_excludes);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_keyword_requires);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 44:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_keyword_subcommands);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 17},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 17},
  [9] = {.lex_state = 17},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 17},
  [15] = {.lex_state = 17},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 17},
  [21] = {.lex_state = 17},
  [22] = {.lex_state = 17},
  [23] = {.lex_state = 17},
  [24] = {.lex_state = 17},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 17},
  [27] = {.lex_state = 17},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 17},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 17},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 17},
  [34] = {.lex_state = 17},
  [35] = {.lex_state = 17},
  [36] = {.lex_state = 17},
  [37] = {.lex_state = 17},
  [38] = {.lex_state = 17},
  [39] = {.lex_state = 17},
  [40] = {.lex_state = 17},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 17},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 17},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 17},
  [49] = {.lex_state = 17},
  [50] = {.lex_state = 17},
  [51] = {.lex_state = 17},
  [52] = {.lex_state = 17},
  [53] = {.lex_state = 17},
  [54] = {.lex_state = 17},
  [55] = {.lex_state = 17},
  [56] = {.lex_state = 17},
  [57] = {.lex_state = 17},
  [58] = {.lex_state = 17},
  [59] = {.lex_state = 17},
  [60] = {.lex_state = 17},
  [61] = {.lex_state = 17},
  [62] = {.lex_state = 17},
  [63] = {.lex_state = 17},
  [64] = {.lex_state = 17},
  [65] = {.lex_state = 17},
  [66] = {.lex_state = 17},
  [67] = {.lex_state = 17},
  [68] = {.lex_state = 17},
  [69] = {.lex_state = 17},
  [70] = {.lex_state = 17},
  [71] = {.lex_state = 17},
  [72] = {.lex_state = 17},
  [73] = {.lex_state = 17},
  [74] = {.lex_state = 17},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 17},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 17},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 17},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 1},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_doc_comment] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(1),
    [sym_keyword_type] = ACTIONS(1),
    [sym_keyword_opt] = ACTIONS(1),
    [sym_keyword_arg] = ACTIONS(1),
    [sym_keyword_cmd] = ACTIONS(1),
    [sym_keyword_requires] = ACTIONS(1),
    [sym_keyword_excludes] = ACTIONS(1),
    [sym_keyword_effects] = ACTIONS(1),
    [sym_keyword_subcommands] = ACTIONS(1),
    [sym_operator_and] = ACTIONS(1),
    [sym_operator_or] = ACTIONS(1),
    [sym_open_paren] = ACTIONS(1),
    [sym_closed_paren] = ACTIONS(1),
    [sym_open_bracket] = ACTIONS(1),
    [sym_closed_bracket] = ACTIONS(1),
    [sym_open_square] = ACTIONS(1),
    [sym_closed_square] = ACTIONS(1),
    [sym_open_chevron] = ACTIONS(1),
    [sym_closed_chevron] = ACTIONS(1),
    [sym_comma] = ACTIONS(1),
    [sym_range] = ACTIONS(1),
    [sym_int_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_bool_literal] = ACTIONS(1),
    [sym_fat_arrow] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(111),
    [sym__declaration] = STATE(2),
    [sym_type_declaration] = STATE(2),
    [sym_opt_declaration] = STATE(2),
    [sym_arg_declaration] = STATE(2),
    [sym_cmd_declaration] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(7),
    [sym_keyword_type] = ACTIONS(9),
    [sym_keyword_opt] = ACTIONS(11),
    [sym_keyword_arg] = ACTIONS(13),
    [sym_keyword_cmd] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      sym_keyword_type,
    ACTIONS(11), 1,
      sym_keyword_opt,
    ACTIONS(13), 1,
      sym_keyword_arg,
    ACTIONS(15), 1,
      sym_keyword_cmd,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_doc_comment,
    ACTIONS(21), 1,
      sym_line_comment,
    STATE(4), 6,
      sym__declaration,
      sym_type_declaration,
      sym_opt_declaration,
      sym_arg_declaration,
      sym_cmd_declaration,
      aux_sym_source_file_repeat1,
  [30] = 8,
    ACTIONS(23), 1,
      sym_doc_comment,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      sym_keyword_type,
    ACTIONS(29), 1,
      sym_keyword_opt,
    ACTIONS(31), 1,
      sym_keyword_arg,
    ACTIONS(33), 1,
      sym_keyword_cmd,
    ACTIONS(35), 1,
      sym_closed_bracket,
    STATE(6), 6,
      sym__declaration,
      sym_type_declaration,
      sym_opt_declaration,
      sym_arg_declaration,
      sym_cmd_declaration,
      aux_sym_source_file_repeat1,
  [60] = 8,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      sym_doc_comment,
    ACTIONS(42), 1,
      sym_line_comment,
    ACTIONS(45), 1,
      sym_keyword_type,
    ACTIONS(48), 1,
      sym_keyword_opt,
    ACTIONS(51), 1,
      sym_keyword_arg,
    ACTIONS(54), 1,
      sym_keyword_cmd,
    STATE(4), 6,
      sym__declaration,
      sym_type_declaration,
      sym_opt_declaration,
      sym_arg_declaration,
      sym_cmd_declaration,
      aux_sym_source_file_repeat1,
  [90] = 8,
    ACTIONS(27), 1,
      sym_keyword_type,
    ACTIONS(29), 1,
      sym_keyword_opt,
    ACTIONS(31), 1,
      sym_keyword_arg,
    ACTIONS(33), 1,
      sym_keyword_cmd,
    ACTIONS(57), 1,
      sym_doc_comment,
    ACTIONS(59), 1,
      sym_line_comment,
    ACTIONS(61), 1,
      sym_closed_bracket,
    STATE(3), 6,
      sym__declaration,
      sym_type_declaration,
      sym_opt_declaration,
      sym_arg_declaration,
      sym_cmd_declaration,
      aux_sym_source_file_repeat1,
  [120] = 8,
    ACTIONS(37), 1,
      sym_closed_bracket,
    ACTIONS(63), 1,
      sym_doc_comment,
    ACTIONS(66), 1,
      sym_line_comment,
    ACTIONS(69), 1,
      sym_keyword_type,
    ACTIONS(72), 1,
      sym_keyword_opt,
    ACTIONS(75), 1,
      sym_keyword_arg,
    ACTIONS(78), 1,
      sym_keyword_cmd,
    STATE(6), 6,
      sym__declaration,
      sym_type_declaration,
      sym_opt_declaration,
      sym_arg_declaration,
      sym_cmd_declaration,
      aux_sym_source_file_repeat1,
  [150] = 8,
    ACTIONS(27), 1,
      sym_keyword_type,
    ACTIONS(29), 1,
      sym_keyword_opt,
    ACTIONS(31), 1,
      sym_keyword_arg,
    ACTIONS(33), 1,
      sym_keyword_cmd,
    ACTIONS(81), 1,
      sym_doc_comment,
    ACTIONS(83), 1,
      sym_line_comment,
    ACTIONS(85), 1,
      sym_closed_bracket,
    STATE(8), 6,
      sym__declaration,
      sym_type_declaration,
      sym_opt_declaration,
      sym_arg_declaration,
      sym_cmd_declaration,
      aux_sym_source_file_repeat1,
  [180] = 8,
    ACTIONS(23), 1,
      sym_doc_comment,
    ACTIONS(25), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      sym_keyword_type,
    ACTIONS(29), 1,
      sym_keyword_opt,
    ACTIONS(31), 1,
      sym_keyword_arg,
    ACTIONS(33), 1,
      sym_keyword_cmd,
    ACTIONS(87), 1,
      sym_closed_bracket,
    STATE(6), 6,
      sym__declaration,
      sym_type_declaration,
      sym_opt_declaration,
      sym_arg_declaration,
      sym_cmd_declaration,
      aux_sym_source_file_repeat1,
  [210] = 4,
    ACTIONS(91), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      sym_operator_or,
    STATE(9), 1,
      aux_sym_anonymous_enum_expression_repeat1,
    ACTIONS(89), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_square,
      sym_closed_chevron,
  [230] = 6,
    ACTIONS(96), 1,
      sym_keyword_requires,
    ACTIONS(98), 1,
      sym_keyword_excludes,
    ACTIONS(100), 1,
      sym_keyword_effects,
    ACTIONS(102), 1,
      sym_keyword_subcommands,
    ACTIONS(104), 1,
      sym_closed_square,
    STATE(13), 6,
      sym__constraint_declaration,
      sym_requires_clause,
      sym_excludes_clause,
      sym_effects_clause,
      sym_subcommands_clause,
      aux_sym_constraint_block_repeat1,
  [254] = 6,
    ACTIONS(108), 1,
      sym_line_comment,
    ACTIONS(110), 1,
      sym_open_bracket,
    ACTIONS(112), 1,
      sym_open_square,
    STATE(33), 1,
      sym_constraint_block,
    STATE(72), 1,
      sym_declaration_block,
    ACTIONS(106), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [278] = 4,
    ACTIONS(116), 1,
      sym_line_comment,
    ACTIONS(118), 1,
      sym_operator_or,
    STATE(14), 1,
      aux_sym_anonymous_enum_expression_repeat1,
    ACTIONS(114), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_square,
      sym_closed_chevron,
  [298] = 6,
    ACTIONS(96), 1,
      sym_keyword_requires,
    ACTIONS(98), 1,
      sym_keyword_excludes,
    ACTIONS(100), 1,
      sym_keyword_effects,
    ACTIONS(102), 1,
      sym_keyword_subcommands,
    ACTIONS(120), 1,
      sym_closed_square,
    STATE(15), 6,
      sym__constraint_declaration,
      sym_requires_clause,
      sym_excludes_clause,
      sym_effects_clause,
      sym_subcommands_clause,
      aux_sym_constraint_block_repeat1,
  [322] = 4,
    ACTIONS(118), 1,
      sym_operator_or,
    ACTIONS(124), 1,
      sym_line_comment,
    STATE(9), 1,
      aux_sym_anonymous_enum_expression_repeat1,
    ACTIONS(122), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_square,
      sym_closed_chevron,
  [342] = 6,
    ACTIONS(126), 1,
      sym_keyword_requires,
    ACTIONS(129), 1,
      sym_keyword_excludes,
    ACTIONS(132), 1,
      sym_keyword_effects,
    ACTIONS(135), 1,
      sym_keyword_subcommands,
    ACTIONS(138), 1,
      sym_closed_square,
    STATE(15), 6,
      sym__constraint_declaration,
      sym_requires_clause,
      sym_excludes_clause,
      sym_effects_clause,
      sym_subcommands_clause,
      aux_sym_constraint_block_repeat1,
  [366] = 6,
    ACTIONS(108), 1,
      sym_line_comment,
    ACTIONS(140), 1,
      sym_open_bracket,
    ACTIONS(142), 1,
      sym_open_square,
    STATE(25), 1,
      sym_constraint_block,
    STATE(68), 1,
      sym_declaration_block,
    ACTIONS(106), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [390] = 6,
    ACTIONS(96), 1,
      sym_keyword_requires,
    ACTIONS(98), 1,
      sym_keyword_excludes,
    ACTIONS(100), 1,
      sym_keyword_effects,
    ACTIONS(102), 1,
      sym_keyword_subcommands,
    ACTIONS(144), 1,
      sym_closed_square,
    STATE(18), 6,
      sym__constraint_declaration,
      sym_requires_clause,
      sym_excludes_clause,
      sym_effects_clause,
      sym_subcommands_clause,
      aux_sym_constraint_block_repeat1,
  [414] = 6,
    ACTIONS(96), 1,
      sym_keyword_requires,
    ACTIONS(98), 1,
      sym_keyword_excludes,
    ACTIONS(100), 1,
      sym_keyword_effects,
    ACTIONS(102), 1,
      sym_keyword_subcommands,
    ACTIONS(146), 1,
      sym_closed_square,
    STATE(15), 6,
      sym__constraint_declaration,
      sym_requires_clause,
      sym_excludes_clause,
      sym_effects_clause,
      sym_subcommands_clause,
      aux_sym_constraint_block_repeat1,
  [438] = 2,
    ACTIONS(150), 1,
      sym_line_comment,
    ACTIONS(148), 9,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_operator_or,
      sym_open_square,
      sym_closed_chevron,
  [453] = 2,
    ACTIONS(91), 1,
      sym_line_comment,
    ACTIONS(89), 9,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_operator_or,
      sym_open_square,
      sym_closed_chevron,
  [468] = 4,
    ACTIONS(116), 1,
      sym_line_comment,
    ACTIONS(152), 1,
      sym_operator_or,
    STATE(22), 1,
      aux_sym_anonymous_enum_expression_repeat1,
    ACTIONS(114), 7,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
      sym_open_square,
  [487] = 4,
    ACTIONS(124), 1,
      sym_line_comment,
    ACTIONS(152), 1,
      sym_operator_or,
    STATE(23), 1,
      aux_sym_anonymous_enum_expression_repeat1,
    ACTIONS(122), 7,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
      sym_open_square,
  [506] = 4,
    ACTIONS(91), 1,
      sym_line_comment,
    ACTIONS(154), 1,
      sym_operator_or,
    STATE(23), 1,
      aux_sym_anonymous_enum_expression_repeat1,
    ACTIONS(89), 7,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
      sym_open_square,
  [525] = 3,
    ACTIONS(159), 1,
      sym_line_comment,
    ACTIONS(161), 1,
      sym_open_chevron,
    ACTIONS(157), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_square,
      sym_closed_chevron,
  [542] = 4,
    ACTIONS(140), 1,
      sym_open_bracket,
    ACTIONS(165), 1,
      sym_line_comment,
    STATE(61), 1,
      sym_declaration_block,
    ACTIONS(163), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [560] = 2,
    ACTIONS(169), 1,
      sym_line_comment,
    ACTIONS(167), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_open_square,
  [574] = 4,
    ACTIONS(112), 1,
      sym_open_square,
    ACTIONS(173), 1,
      sym_line_comment,
    STATE(57), 1,
      sym_constraint_block,
    ACTIONS(171), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [592] = 5,
    ACTIONS(175), 1,
      sym_named_identifier,
    STATE(12), 1,
      sym_literals,
    ACTIONS(177), 2,
      sym_int_literal,
      sym_bool_literal,
    ACTIONS(179), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(46), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [612] = 2,
    ACTIONS(183), 1,
      sym_line_comment,
    ACTIONS(181), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_open_square,
  [626] = 5,
    ACTIONS(175), 1,
      sym_named_identifier,
    STATE(12), 1,
      sym_literals,
    ACTIONS(177), 2,
      sym_int_literal,
      sym_bool_literal,
    ACTIONS(179), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(27), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [646] = 2,
    ACTIONS(187), 1,
      sym_line_comment,
    ACTIONS(185), 8,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_square,
      sym_closed_chevron,
  [660] = 5,
    ACTIONS(175), 1,
      sym_named_identifier,
    STATE(12), 1,
      sym_literals,
    ACTIONS(177), 2,
      sym_int_literal,
      sym_bool_literal,
    ACTIONS(179), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(48), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [680] = 4,
    ACTIONS(110), 1,
      sym_open_bracket,
    ACTIONS(165), 1,
      sym_line_comment,
    STATE(63), 1,
      sym_declaration_block,
    ACTIONS(163), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [698] = 3,
    ACTIONS(159), 1,
      sym_line_comment,
    ACTIONS(189), 1,
      sym_open_chevron,
    ACTIONS(157), 7,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
      sym_open_square,
  [714] = 2,
    ACTIONS(150), 1,
      sym_line_comment,
    ACTIONS(148), 8,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_operator_or,
      sym_closed_bracket,
      sym_open_square,
  [728] = 4,
    ACTIONS(142), 1,
      sym_open_square,
    ACTIONS(193), 1,
      sym_line_comment,
    STATE(62), 1,
      sym_constraint_block,
    ACTIONS(191), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [746] = 4,
    ACTIONS(142), 1,
      sym_open_square,
    ACTIONS(197), 1,
      sym_line_comment,
    STATE(64), 1,
      sym_constraint_block,
    ACTIONS(195), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [764] = 4,
    ACTIONS(142), 1,
      sym_open_square,
    ACTIONS(173), 1,
      sym_line_comment,
    STATE(65), 1,
      sym_constraint_block,
    ACTIONS(171), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [782] = 2,
    ACTIONS(169), 1,
      sym_line_comment,
    ACTIONS(167), 8,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_bracket,
      sym_open_square,
  [796] = 2,
    ACTIONS(91), 1,
      sym_line_comment,
    ACTIONS(89), 8,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_operator_or,
      sym_closed_bracket,
      sym_open_square,
  [810] = 5,
    ACTIONS(175), 1,
      sym_named_identifier,
    STATE(12), 1,
      sym_literals,
    ACTIONS(177), 2,
      sym_int_literal,
      sym_bool_literal,
    ACTIONS(179), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(102), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [830] = 2,
    ACTIONS(183), 1,
      sym_line_comment,
    ACTIONS(181), 8,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_bracket,
      sym_open_square,
  [844] = 5,
    ACTIONS(199), 1,
      sym_named_identifier,
    STATE(21), 1,
      sym_literals,
    ACTIONS(201), 2,
      sym_int_literal,
      sym_bool_literal,
    ACTIONS(203), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(36), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [864] = 5,
    ACTIONS(199), 1,
      sym_named_identifier,
    STATE(21), 1,
      sym_literals,
    ACTIONS(201), 2,
      sym_int_literal,
      sym_bool_literal,
    ACTIONS(203), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(37), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [884] = 5,
    ACTIONS(199), 1,
      sym_named_identifier,
    STATE(21), 1,
      sym_literals,
    ACTIONS(201), 2,
      sym_int_literal,
      sym_bool_literal,
    ACTIONS(203), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(38), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [904] = 4,
    ACTIONS(112), 1,
      sym_open_square,
    ACTIONS(197), 1,
      sym_line_comment,
    STATE(73), 1,
      sym_constraint_block,
    ACTIONS(195), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [922] = 5,
    ACTIONS(175), 1,
      sym_named_identifier,
    STATE(12), 1,
      sym_literals,
    ACTIONS(177), 2,
      sym_int_literal,
      sym_bool_literal,
    ACTIONS(179), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(120), 3,
      sym__type_expression,
      sym_nested_type,
      sym_anonymous_enum_expression,
  [942] = 4,
    ACTIONS(112), 1,
      sym_open_square,
    ACTIONS(193), 1,
      sym_line_comment,
    STATE(70), 1,
      sym_constraint_block,
    ACTIONS(191), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [960] = 1,
    ACTIONS(205), 8,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_keyword_subcommands,
      sym_operator_and,
      sym_operator_or,
      sym_closed_paren,
      sym_closed_square,
  [971] = 2,
    ACTIONS(209), 1,
      sym_line_comment,
    ACTIONS(207), 7,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_bracket,
  [984] = 2,
    ACTIONS(213), 1,
      sym_line_comment,
    ACTIONS(211), 7,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
      sym_closed_bracket,
  [997] = 1,
    ACTIONS(215), 8,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_keyword_subcommands,
      sym_operator_and,
      sym_operator_or,
      sym_closed_paren,
      sym_closed_square,
  [1008] = 2,
    ACTIONS(219), 1,
      sym_operator_and,
    ACTIONS(217), 7,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_keyword_subcommands,
      sym_operator_or,
      sym_closed_paren,
      sym_closed_square,
  [1021] = 2,
    ACTIONS(213), 1,
      sym_line_comment,
    ACTIONS(211), 7,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
  [1034] = 2,
    ACTIONS(187), 1,
      sym_line_comment,
    ACTIONS(185), 7,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
      sym_open_square,
  [1047] = 2,
    ACTIONS(209), 1,
      sym_line_comment,
    ACTIONS(207), 7,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_open_bracket,
  [1060] = 2,
    ACTIONS(223), 1,
      sym_line_comment,
    ACTIONS(221), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [1072] = 3,
    ACTIONS(219), 1,
      sym_operator_and,
    ACTIONS(227), 1,
      sym_operator_or,
    ACTIONS(225), 5,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_keyword_subcommands,
      sym_closed_square,
  [1086] = 3,
    ACTIONS(219), 1,
      sym_operator_and,
    ACTIONS(227), 1,
      sym_operator_or,
    ACTIONS(229), 5,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_keyword_subcommands,
      sym_closed_square,
  [1100] = 3,
    ACTIONS(219), 1,
      sym_operator_and,
    ACTIONS(227), 1,
      sym_operator_or,
    ACTIONS(231), 5,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_keyword_subcommands,
      sym_closed_square,
  [1114] = 2,
    ACTIONS(235), 1,
      sym_line_comment,
    ACTIONS(233), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [1126] = 2,
    ACTIONS(239), 1,
      sym_line_comment,
    ACTIONS(237), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [1138] = 2,
    ACTIONS(235), 1,
      sym_line_comment,
    ACTIONS(233), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [1150] = 2,
    ACTIONS(243), 1,
      sym_line_comment,
    ACTIONS(241), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [1162] = 2,
    ACTIONS(223), 1,
      sym_line_comment,
    ACTIONS(221), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [1174] = 2,
    ACTIONS(247), 1,
      sym_line_comment,
    ACTIONS(245), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [1186] = 2,
    ACTIONS(251), 1,
      sym_line_comment,
    ACTIONS(249), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [1198] = 2,
    ACTIONS(165), 1,
      sym_line_comment,
    ACTIONS(163), 6,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
      sym_closed_bracket,
  [1210] = 2,
    ACTIONS(251), 1,
      sym_line_comment,
    ACTIONS(249), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [1222] = 2,
    ACTIONS(239), 1,
      sym_line_comment,
    ACTIONS(237), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [1234] = 2,
    ACTIONS(247), 1,
      sym_line_comment,
    ACTIONS(245), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [1246] = 2,
    ACTIONS(165), 1,
      sym_line_comment,
    ACTIONS(163), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [1258] = 2,
    ACTIONS(243), 1,
      sym_line_comment,
    ACTIONS(241), 6,
      ts_builtin_sym_end,
      sym_doc_comment,
      sym_keyword_type,
      sym_keyword_opt,
      sym_keyword_arg,
      sym_keyword_cmd,
  [1270] = 3,
    ACTIONS(219), 1,
      sym_operator_and,
    ACTIONS(227), 1,
      sym_operator_or,
    ACTIONS(253), 5,
      sym_keyword_requires,
      sym_keyword_excludes,
      sym_keyword_effects,
      sym_keyword_subcommands,
      sym_closed_square,
  [1284] = 3,
    ACTIONS(255), 1,
      sym_open_paren,
    ACTIONS(257), 1,
      sym_named_identifier,
    STATE(52), 4,
      sym_and_expression,
      sym_or_expression,
      sym_paren_expression,
      sym__boolean_expression,
  [1297] = 3,
    ACTIONS(255), 1,
      sym_open_paren,
    ACTIONS(259), 1,
      sym_named_identifier,
    STATE(88), 4,
      sym_and_expression,
      sym_or_expression,
      sym_paren_expression,
      sym__boolean_expression,
  [1310] = 3,
    ACTIONS(255), 1,
      sym_open_paren,
    ACTIONS(261), 1,
      sym_named_identifier,
    STATE(59), 4,
      sym_and_expression,
      sym_or_expression,
      sym_paren_expression,
      sym__boolean_expression,
  [1323] = 3,
    ACTIONS(255), 1,
      sym_open_paren,
    ACTIONS(263), 1,
      sym_named_identifier,
    STATE(53), 4,
      sym_and_expression,
      sym_or_expression,
      sym_paren_expression,
      sym__boolean_expression,
  [1336] = 3,
    ACTIONS(255), 1,
      sym_open_paren,
    ACTIONS(265), 1,
      sym_named_identifier,
    STATE(60), 4,
      sym_and_expression,
      sym_or_expression,
      sym_paren_expression,
      sym__boolean_expression,
  [1349] = 3,
    ACTIONS(255), 1,
      sym_open_paren,
    ACTIONS(267), 1,
      sym_named_identifier,
    STATE(58), 4,
      sym_and_expression,
      sym_or_expression,
      sym_paren_expression,
      sym__boolean_expression,
  [1362] = 3,
    ACTIONS(255), 1,
      sym_open_paren,
    ACTIONS(269), 1,
      sym_named_identifier,
    STATE(74), 4,
      sym_and_expression,
      sym_or_expression,
      sym_paren_expression,
      sym__boolean_expression,
  [1375] = 3,
    ACTIONS(177), 1,
      sym_int_literal,
    STATE(20), 1,
      sym_literals,
    ACTIONS(179), 3,
      sym_float_literal,
      sym_string_literal,
      sym_bool_literal,
  [1387] = 3,
    ACTIONS(201), 1,
      sym_int_literal,
    STATE(40), 1,
      sym_literals,
    ACTIONS(203), 3,
      sym_float_literal,
      sym_string_literal,
      sym_bool_literal,
  [1399] = 3,
    ACTIONS(271), 1,
      sym_closed_paren,
    ACTIONS(273), 1,
      sym_comma,
    STATE(90), 1,
      aux_sym_opt_unit_repeat1,
  [1409] = 3,
    ACTIONS(273), 1,
      sym_comma,
    ACTIONS(275), 1,
      sym_closed_paren,
    STATE(90), 1,
      aux_sym_opt_unit_repeat1,
  [1419] = 3,
    ACTIONS(273), 1,
      sym_comma,
    ACTIONS(277), 1,
      sym_closed_paren,
    STATE(90), 1,
      aux_sym_opt_unit_repeat1,
  [1429] = 3,
    ACTIONS(273), 1,
      sym_comma,
    ACTIONS(279), 1,
      sym_closed_paren,
    STATE(86), 1,
      aux_sym_opt_unit_repeat1,
  [1439] = 3,
    ACTIONS(219), 1,
      sym_operator_and,
    ACTIONS(227), 1,
      sym_operator_or,
    ACTIONS(281), 1,
      sym_closed_paren,
  [1449] = 3,
    ACTIONS(273), 1,
      sym_comma,
    ACTIONS(283), 1,
      sym_closed_paren,
    STATE(84), 1,
      aux_sym_opt_unit_repeat1,
  [1459] = 3,
    ACTIONS(285), 1,
      sym_closed_paren,
    ACTIONS(287), 1,
      sym_comma,
    STATE(90), 1,
      aux_sym_opt_unit_repeat1,
  [1469] = 3,
    ACTIONS(273), 1,
      sym_comma,
    ACTIONS(290), 1,
      sym_closed_paren,
    STATE(85), 1,
      aux_sym_opt_unit_repeat1,
  [1479] = 2,
    ACTIONS(292), 1,
      sym_closed_paren,
    ACTIONS(294), 1,
      sym_int_literal,
  [1486] = 2,
    ACTIONS(296), 1,
      sym_named_identifier,
    STATE(123), 1,
      sym_arg_unit,
  [1493] = 2,
    ACTIONS(298), 1,
      sym_closed_paren,
    ACTIONS(300), 1,
      sym_int_literal,
  [1500] = 2,
    ACTIONS(302), 1,
      sym_named_identifier,
    STATE(116), 1,
      sym_opt_unit,
  [1507] = 2,
    ACTIONS(296), 1,
      sym_named_identifier,
    STATE(119), 1,
      sym_arg_unit,
  [1514] = 2,
    ACTIONS(304), 1,
      sym_named_identifier,
    STATE(11), 1,
      sym_cmd_unit,
  [1521] = 2,
    ACTIONS(306), 1,
      sym_named_identifier,
    STATE(16), 1,
      sym_cmd_unit,
  [1528] = 2,
    ACTIONS(308), 1,
      sym_range,
    ACTIONS(310), 1,
      sym_int_literal,
  [1535] = 1,
    ACTIONS(285), 2,
      sym_closed_paren,
      sym_comma,
  [1540] = 2,
    ACTIONS(302), 1,
      sym_named_identifier,
    STATE(122), 1,
      sym_opt_unit,
  [1547] = 1,
    ACTIONS(312), 1,
      sym_closed_chevron,
  [1551] = 1,
    ACTIONS(314), 1,
      sym_fat_arrow,
  [1555] = 1,
    ACTIONS(316), 1,
      sym_closed_paren,
  [1559] = 1,
    ACTIONS(318), 1,
      sym_open_paren,
  [1563] = 1,
    ACTIONS(320), 1,
      sym_range,
  [1567] = 1,
    ACTIONS(322), 1,
      sym_string_literal,
  [1571] = 1,
    ACTIONS(324), 1,
      sym_fat_arrow,
  [1575] = 1,
    ACTIONS(326), 1,
      sym_open_paren,
  [1579] = 1,
    ACTIONS(328), 1,
      sym_named_identifier,
  [1583] = 1,
    ACTIONS(330), 1,
      ts_builtin_sym_end,
  [1587] = 1,
    ACTIONS(332), 1,
      sym_string_literal,
  [1591] = 1,
    ACTIONS(334), 1,
      sym_open_paren,
  [1595] = 1,
    ACTIONS(336), 1,
      sym_fat_arrow,
  [1599] = 1,
    ACTIONS(338), 1,
      sym_string_literal,
  [1603] = 1,
    ACTIONS(340), 1,
      sym_fat_arrow,
  [1607] = 1,
    ACTIONS(342), 1,
      sym_fat_arrow,
  [1611] = 1,
    ACTIONS(344), 1,
      sym_fat_arrow,
  [1615] = 1,
    ACTIONS(346), 1,
      sym_fat_arrow,
  [1619] = 1,
    ACTIONS(348), 1,
      sym_closed_chevron,
  [1623] = 1,
    ACTIONS(350), 1,
      sym_fat_arrow,
  [1627] = 1,
    ACTIONS(352), 1,
      sym_fat_arrow,
  [1631] = 1,
    ACTIONS(354), 1,
      sym_fat_arrow,
  [1635] = 1,
    ACTIONS(356), 1,
      sym_string_literal,
  [1639] = 1,
    ACTIONS(358), 1,
      sym_closed_paren,
  [1643] = 1,
    ACTIONS(360), 1,
      sym_named_identifier,
  [1647] = 1,
    ACTIONS(362), 1,
      sym_fat_arrow,
  [1651] = 1,
    ACTIONS(364), 1,
      sym_fat_arrow,
  [1655] = 1,
    ACTIONS(366), 1,
      sym_open_paren,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 120,
  [SMALL_STATE(7)] = 150,
  [SMALL_STATE(8)] = 180,
  [SMALL_STATE(9)] = 210,
  [SMALL_STATE(10)] = 230,
  [SMALL_STATE(11)] = 254,
  [SMALL_STATE(12)] = 278,
  [SMALL_STATE(13)] = 298,
  [SMALL_STATE(14)] = 322,
  [SMALL_STATE(15)] = 342,
  [SMALL_STATE(16)] = 366,
  [SMALL_STATE(17)] = 390,
  [SMALL_STATE(18)] = 414,
  [SMALL_STATE(19)] = 438,
  [SMALL_STATE(20)] = 453,
  [SMALL_STATE(21)] = 468,
  [SMALL_STATE(22)] = 487,
  [SMALL_STATE(23)] = 506,
  [SMALL_STATE(24)] = 525,
  [SMALL_STATE(25)] = 542,
  [SMALL_STATE(26)] = 560,
  [SMALL_STATE(27)] = 574,
  [SMALL_STATE(28)] = 592,
  [SMALL_STATE(29)] = 612,
  [SMALL_STATE(30)] = 626,
  [SMALL_STATE(31)] = 646,
  [SMALL_STATE(32)] = 660,
  [SMALL_STATE(33)] = 680,
  [SMALL_STATE(34)] = 698,
  [SMALL_STATE(35)] = 714,
  [SMALL_STATE(36)] = 728,
  [SMALL_STATE(37)] = 746,
  [SMALL_STATE(38)] = 764,
  [SMALL_STATE(39)] = 782,
  [SMALL_STATE(40)] = 796,
  [SMALL_STATE(41)] = 810,
  [SMALL_STATE(42)] = 830,
  [SMALL_STATE(43)] = 844,
  [SMALL_STATE(44)] = 864,
  [SMALL_STATE(45)] = 884,
  [SMALL_STATE(46)] = 904,
  [SMALL_STATE(47)] = 922,
  [SMALL_STATE(48)] = 942,
  [SMALL_STATE(49)] = 960,
  [SMALL_STATE(50)] = 971,
  [SMALL_STATE(51)] = 984,
  [SMALL_STATE(52)] = 997,
  [SMALL_STATE(53)] = 1008,
  [SMALL_STATE(54)] = 1021,
  [SMALL_STATE(55)] = 1034,
  [SMALL_STATE(56)] = 1047,
  [SMALL_STATE(57)] = 1060,
  [SMALL_STATE(58)] = 1072,
  [SMALL_STATE(59)] = 1086,
  [SMALL_STATE(60)] = 1100,
  [SMALL_STATE(61)] = 1114,
  [SMALL_STATE(62)] = 1126,
  [SMALL_STATE(63)] = 1138,
  [SMALL_STATE(64)] = 1150,
  [SMALL_STATE(65)] = 1162,
  [SMALL_STATE(66)] = 1174,
  [SMALL_STATE(67)] = 1186,
  [SMALL_STATE(68)] = 1198,
  [SMALL_STATE(69)] = 1210,
  [SMALL_STATE(70)] = 1222,
  [SMALL_STATE(71)] = 1234,
  [SMALL_STATE(72)] = 1246,
  [SMALL_STATE(73)] = 1258,
  [SMALL_STATE(74)] = 1270,
  [SMALL_STATE(75)] = 1284,
  [SMALL_STATE(76)] = 1297,
  [SMALL_STATE(77)] = 1310,
  [SMALL_STATE(78)] = 1323,
  [SMALL_STATE(79)] = 1336,
  [SMALL_STATE(80)] = 1349,
  [SMALL_STATE(81)] = 1362,
  [SMALL_STATE(82)] = 1375,
  [SMALL_STATE(83)] = 1387,
  [SMALL_STATE(84)] = 1399,
  [SMALL_STATE(85)] = 1409,
  [SMALL_STATE(86)] = 1419,
  [SMALL_STATE(87)] = 1429,
  [SMALL_STATE(88)] = 1439,
  [SMALL_STATE(89)] = 1449,
  [SMALL_STATE(90)] = 1459,
  [SMALL_STATE(91)] = 1469,
  [SMALL_STATE(92)] = 1479,
  [SMALL_STATE(93)] = 1486,
  [SMALL_STATE(94)] = 1493,
  [SMALL_STATE(95)] = 1500,
  [SMALL_STATE(96)] = 1507,
  [SMALL_STATE(97)] = 1514,
  [SMALL_STATE(98)] = 1521,
  [SMALL_STATE(99)] = 1528,
  [SMALL_STATE(100)] = 1535,
  [SMALL_STATE(101)] = 1540,
  [SMALL_STATE(102)] = 1547,
  [SMALL_STATE(103)] = 1551,
  [SMALL_STATE(104)] = 1555,
  [SMALL_STATE(105)] = 1559,
  [SMALL_STATE(106)] = 1563,
  [SMALL_STATE(107)] = 1567,
  [SMALL_STATE(108)] = 1571,
  [SMALL_STATE(109)] = 1575,
  [SMALL_STATE(110)] = 1579,
  [SMALL_STATE(111)] = 1583,
  [SMALL_STATE(112)] = 1587,
  [SMALL_STATE(113)] = 1591,
  [SMALL_STATE(114)] = 1595,
  [SMALL_STATE(115)] = 1599,
  [SMALL_STATE(116)] = 1603,
  [SMALL_STATE(117)] = 1607,
  [SMALL_STATE(118)] = 1611,
  [SMALL_STATE(119)] = 1615,
  [SMALL_STATE(120)] = 1619,
  [SMALL_STATE(121)] = 1623,
  [SMALL_STATE(122)] = 1627,
  [SMALL_STATE(123)] = 1631,
  [SMALL_STATE(124)] = 1635,
  [SMALL_STATE(125)] = 1639,
  [SMALL_STATE(126)] = 1643,
  [SMALL_STATE(127)] = 1647,
  [SMALL_STATE(128)] = 1651,
  [SMALL_STATE(129)] = 1655,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(126),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_anonymous_enum_expression_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_anonymous_enum_expression_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_anonymous_enum_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_declaration, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_declaration, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_enum_expression, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonymous_enum_expression, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anonymous_enum_expression, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anonymous_enum_expression, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constraint_block_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literals, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literals, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_anonymous_enum_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_expression, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type_expression, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_declaration, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_declaration, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_unit, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_unit, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_declaration, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_declaration, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_unit, 5, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_unit, 5, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_type, 4, 0, 3),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_type, 4, 0, 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 4, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_declaration, 4, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opt_declaration, 4, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opt_declaration, 4, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expression, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_block, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_block, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_block, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_block, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and_expression, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_expression, 3, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_declaration, 5, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_declaration, 5, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subcommands_clause, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_excludes_clause, 2, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_effects_clause, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd_declaration, 4, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd_declaration, 4, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 5, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_declaration, 5, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opt_declaration, 5, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opt_declaration, 5, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_block, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_block, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_block, 3, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_block, 3, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_clause, 2, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_opt_unit_repeat1, 2, 0, 0),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_opt_unit_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_unit, 4, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opt_unit, 4, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [330] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opt_unit, 5, 0, 0),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_unit, 5, 0, 1),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_unit, 5, 0, 2),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [364] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_unit, 6, 0, 4),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_clispec(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "clispec",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 4,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
